INSERT INTO `english_test`.`pregunta` (`pregunta`, `tipo_pregunta`) VALUES ('How should you address this young couple?',0);
INSERT INTO `english_test`.`pregunta` (`pregunta`, `tipo_pregunta`) VALUES ('Paul and Linda´s room is on the third floor. They don´t want to walk, so they’ll',0);
INSERT INTO `english_test`.`pregunta` (`pregunta`, `tipo_pregunta`) VALUES ('If the hotel is overbooked, what should you say to a guest that wants a room? I’m sorry, …',0);
INSERT INTO `english_test`.`pregunta` (`pregunta`, `tipo_pregunta`) VALUES ('After having lunch at the restaurant, they should ask for',0);

INSERT INTO `english_test`.`respuesta` (`respuesta`, `ponderacion`, `pregunta_id`) VALUES ('Lady and gentleman Smith',0, 1);
INSERT INTO `english_test`.`respuesta` (`respuesta`, `ponderacion`, `pregunta_id`) VALUES ('Miss and Mr. Smith',0, 1);
INSERT INTO `english_test`.`respuesta` (`respuesta`, `ponderacion`, `pregunta_id`) VALUES ('Check out',0, 2);
INSERT INTO `english_test`.`respuesta` (`respuesta`, `ponderacion`, `pregunta_id`) VALUES ('Check in',0, 2);
INSERT INTO `english_test`.`respuesta` (`respuesta`, `ponderacion`, `pregunta_id`) VALUES ('Check over',0, 2);
INSERT INTO `english_test`.`respuesta` (`respuesta`, `ponderacion`, `pregunta_id`) VALUES ('Check on',0, 2);
INSERT INTO `english_test`.`respuesta` (`respuesta`, `ponderacion`, `pregunta_id`) VALUES ('the corridor',0, 3);
INSERT INTO `english_test`.`respuesta` (`respuesta`, `ponderacion`, `pregunta_id`) VALUES ('the car',0, 3);
INSERT INTO `english_test`.`respuesta` (`respuesta`, `ponderacion`, `pregunta_id`) VALUES ('the stairway',0, 3);
INSERT INTO `english_test`.`respuesta` (`respuesta`, `ponderacion`, `pregunta_id`) VALUES ('the elevator',0, 3);
INSERT INTO `english_test`.`respuesta` (`respuesta`, `ponderacion`, `pregunta_id`) VALUES ('we don’t have any vacancies.',0, 4);
INSERT INTO `english_test`.`respuesta` (`respuesta`, `ponderacion`, `pregunta_id`) VALUES ('there are available rooms.',0, 4);
INSERT INTO `english_test`.`respuesta` (`respuesta`, `ponderacion`, `pregunta_id`) VALUES ('we only have one vacancy room.',0, 4);
INSERT INTO `english_test`.`respuesta` (`respuesta`, `ponderacion`, `pregunta_id`) VALUES ('come back soon.',0, 4);
INSERT INTO `english_test`.`respuesta` (`respuesta`, `ponderacion`, `pregunta_id`) VALUES ('the menu',0, 5);
INSERT INTO `english_test`.`respuesta` (`respuesta`, `ponderacion`, `pregunta_id`) VALUES ('the bill',0, 5);
INSERT INTO `english_test`.`respuesta` (`respuesta`, `ponderacion`, `pregunta_id`) VALUES ('the tip',0, 5);
INSERT INTO `english_test`.`respuesta` (`respuesta`, `ponderacion`, `pregunta_id`) VALUES ('the order',0, 5);