/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import controlador.ControladorAgrupar;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author CFManuel
 */
public class Agrupar extends javax.swing.JFrame {

    /**
     * Creates new form Agrupar
     */
    public Agrupar(ControladorAgrupar controlador) {
        initComponents();
        _controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _JPanel = new javax.swing.JPanel();
        _lblInstruccion = new javax.swing.JLabel();
        _lblPregunta = new javax.swing.JLabel();
        terminarExamen = new javax.swing.JButton();
        avanzar = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        _LblGrupo1 = new javax.swing.JLabel();
        _TxtFldGrupo1_2 = new javax.swing.JTextField();
        _TxtFldGrupo1_1 = new javax.swing.JTextField();
        _TxtFldGrupo1_3 = new javax.swing.JTextField();
        _LblGrupo2 = new javax.swing.JLabel();
        _TxtFldGrupo2_2 = new javax.swing.JTextField();
        _TxtFldGrupo2_1 = new javax.swing.JTextField();
        _TxtFldGrupo2_3 = new javax.swing.JTextField();
        _LblGrupo3 = new javax.swing.JLabel();
        _TxtFldGrupo3_2 = new javax.swing.JTextField();
        _TxtFldGrupo3_1 = new javax.swing.JTextField();
        _TxtFldGrupo3_3 = new javax.swing.JTextField();
        _LblGrupo4 = new javax.swing.JLabel();
        _TxtFldGrupo4_2 = new javax.swing.JTextField();
        _TxtFldGrupo4_1 = new javax.swing.JTextField();
        _TxtFldGrupo4_3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _JPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Examen"));
        _JPanel.setName("Examen"); // NOI18N

        _lblInstruccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        _lblInstruccion.setText("Pregunta");

        _lblPregunta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        _lblPregunta.setText("¿Pregunta?");

        terminarExamen.setText("Terminar Examen");
        terminarExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarExamenActionPerformed(evt);
            }
        });

        avanzar.setText("Avanzar >>");
        avanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avanzarActionPerformed(evt);
            }
        });

        regresar.setText("<< Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        _LblGrupo1.setText("Grupo 1");

        _TxtFldGrupo1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _TxtFldGrupo1_3ActionPerformed(evt);
            }
        });

        _LblGrupo2.setText("Grupo 2");

        _TxtFldGrupo2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _TxtFldGrupo2_2ActionPerformed(evt);
            }
        });

        _LblGrupo3.setText("Grupo 3");

        _TxtFldGrupo3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _TxtFldGrupo3_2ActionPerformed(evt);
            }
        });

        _LblGrupo4.setText("Grupo 4");

        javax.swing.GroupLayout _JPanelLayout = new javax.swing.GroupLayout(_JPanel);
        _JPanel.setLayout(_JPanelLayout);
        _JPanelLayout.setHorizontalGroup(
            _JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_JPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(_JPanelLayout.createSequentialGroup()
                        .addComponent(_LblGrupo1)
                        .addGap(18, 18, 18)
                        .addGroup(_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _JPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(terminarExamen))
                            .addGroup(_JPanelLayout.createSequentialGroup()
                                .addGroup(_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(_JPanelLayout.createSequentialGroup()
                                        .addGroup(_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(_TxtFldGrupo1_2, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                            .addComponent(_TxtFldGrupo1_3)
                                            .addComponent(_TxtFldGrupo1_1, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(50, 50, 50)
                                        .addComponent(_LblGrupo2)
                                        .addGap(18, 18, 18)
                                        .addGroup(_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(_TxtFldGrupo2_3, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                            .addComponent(_TxtFldGrupo2_2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(_TxtFldGrupo2_1, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(42, 42, 42)
                                        .addComponent(_LblGrupo3)
                                        .addGap(18, 18, 18)
                                        .addGroup(_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(_TxtFldGrupo3_3)
                                            .addComponent(_TxtFldGrupo3_1)
                                            .addComponent(_TxtFldGrupo3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(34, 34, 34)
                                        .addComponent(_LblGrupo4)
                                        .addGap(18, 18, 18)
                                        .addGroup(_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(_TxtFldGrupo4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(_TxtFldGrupo4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(_TxtFldGrupo4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(_JPanelLayout.createSequentialGroup()
                                        .addGap(409, 409, 409)
                                        .addComponent(regresar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(avanzar)))
                                .addGap(0, 12, Short.MAX_VALUE))))
                    .addGroup(_JPanelLayout.createSequentialGroup()
                        .addGroup(_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_lblInstruccion)
                            .addComponent(_lblPregunta))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        _JPanelLayout.setVerticalGroup(
            _JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_lblInstruccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_lblPregunta)
                .addGap(30, 30, 30)
                .addGroup(_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(_JPanelLayout.createSequentialGroup()
                        .addGroup(_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_TxtFldGrupo1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_TxtFldGrupo2_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_LblGrupo1)
                            .addComponent(_TxtFldGrupo1_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_LblGrupo2)
                            .addComponent(_TxtFldGrupo2_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_TxtFldGrupo1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_TxtFldGrupo2_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(_JPanelLayout.createSequentialGroup()
                        .addGroup(_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_TxtFldGrupo3_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_TxtFldGrupo4_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_LblGrupo3)
                            .addComponent(_TxtFldGrupo3_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_LblGrupo4)
                            .addComponent(_TxtFldGrupo4_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_TxtFldGrupo3_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_TxtFldGrupo4_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addGroup(_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avanzar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(regresar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(terminarExamen)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        _posicion--;
        this.rellenarCamposAnteriores(_preguntas);
    }//GEN-LAST:event_regresarActionPerformed

    private void avanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avanzarActionPerformed
    _posicion++;
    if(_posicion+1>=_preguntas.obtenerNumPreguntas()){
        avanzar.setEnabled(false);
    }
    this.rellenarCampos(_preguntas);
    _preguntas.asignarRespuestasUsuario(this.generarRespuestasUsuario());
    this.vaciarCampos();
    }//GEN-LAST:event_avanzarActionPerformed

    private void terminarExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarExamenActionPerformed
        _preguntas.asignarRespuestasUsuario(this.generarRespuestasUsuario());
        this.calificar();
        JOptionPane.showMessageDialog(null,"Tu calificacion ha sido de " + _calificacion);
        System.exit(0);
    }//GEN-LAST:event_terminarExamenActionPerformed

    private void _TxtFldGrupo1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__TxtFldGrupo1_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__TxtFldGrupo1_3ActionPerformed

    private void _TxtFldGrupo2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__TxtFldGrupo2_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__TxtFldGrupo2_2ActionPerformed

    private void _TxtFldGrupo3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__TxtFldGrupo3_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__TxtFldGrupo3_2ActionPerformed

    public void rellenarCampos(PreguntaAgrupar preguntas){
        ArrayList listaPalabras = new ArrayList();
        ArrayList listaGrupos = new ArrayList();
        String palabras = "";
        int indice = 0;
        _lblInstruccion.setText(preguntas.obtenerInstruccion(_posicion));
        listaPalabras = preguntas.generarRespuestasPropuestas(_posicion);
        listaGrupos = preguntas.obtenerListaGrupos(_posicion);
        
        while(indice<listaPalabras.size()){
            palabras+= listaPalabras.get(indice) + "    ";
            if((indice%7) == 0){
                palabras+= "\n";
            }
            indice++;
        }
        _lblPregunta.setText(palabras);
        _LblGrupo1.setText((String) listaGrupos.get(0));
        _LblGrupo2.setText((String) listaGrupos.get(1));
        _LblGrupo3.setText((String) listaGrupos.get(2));
        _LblGrupo4.setText((String) listaGrupos.get(3));
        
        
        
    }
    
        public void rellenarCamposAnteriores (PreguntaAgrupar preguntas){
        ArrayList listaPalabras = new ArrayList();
        ArrayList listaGrupos = new ArrayList();
        String palabras = "";
        int indice = 0;
        _lblInstruccion.setText(preguntas.obtenerInstruccion(_posicion));
        listaPalabras = preguntas.generarRespuestasPropuestas(_posicion);
        listaGrupos = preguntas.obtenerListaGrupos(_posicion);
        
        while(indice<listaPalabras.size()){
            palabras+= listaPalabras.get(indice) + "    ";
            if((indice%7) == 0){
                palabras+= "\n";
            }
            indice++;
        }
        _lblPregunta.setText(palabras);
        _LblGrupo1.setText((String) listaGrupos.get(0));
        _LblGrupo2.setText((String) listaGrupos.get(1));
        _LblGrupo3.setText((String) listaGrupos.get(2));
        _LblGrupo4.setText((String) listaGrupos.get(3));
        
        _TxtFldGrupo1_1.setText((String)((ArrayList)(preguntas.obtenerRespuestasUsuario(_posicion).obtenerRespuestas().get(0))).get(0));
        _TxtFldGrupo1_2.setText((String)((ArrayList)(preguntas.obtenerRespuestasUsuario(_posicion).obtenerRespuestas().get(0))).get(1));
        _TxtFldGrupo1_3.setText((String)((ArrayList)(preguntas.obtenerRespuestasUsuario(_posicion).obtenerRespuestas().get(0))).get(2));
        _TxtFldGrupo2_1.setText((String)((ArrayList)(preguntas.obtenerRespuestasUsuario(_posicion).obtenerRespuestas().get(1))).get(0));
        _TxtFldGrupo2_2.setText((String)((ArrayList)(preguntas.obtenerRespuestasUsuario(_posicion).obtenerRespuestas().get(1))).get(1));
        _TxtFldGrupo2_3.setText((String)((ArrayList)(preguntas.obtenerRespuestasUsuario(_posicion).obtenerRespuestas().get(1))).get(2));
        _TxtFldGrupo3_1.setText((String)((ArrayList)(preguntas.obtenerRespuestasUsuario(_posicion).obtenerRespuestas().get(2))).get(0));
        _TxtFldGrupo3_2.setText((String)((ArrayList)(preguntas.obtenerRespuestasUsuario(_posicion).obtenerRespuestas().get(2))).get(1));
        _TxtFldGrupo3_3.setText((String)((ArrayList)(preguntas.obtenerRespuestasUsuario(_posicion).obtenerRespuestas().get(2))).get(2));
        _TxtFldGrupo4_1.setText((String)((ArrayList)(preguntas.obtenerRespuestasUsuario(_posicion).obtenerRespuestas().get(3))).get(0));
        _TxtFldGrupo4_2.setText((String)((ArrayList)(preguntas.obtenerRespuestasUsuario(_posicion).obtenerRespuestas().get(3))).get(1));
        _TxtFldGrupo4_3.setText((String)((ArrayList)(preguntas.obtenerRespuestasUsuario(_posicion).obtenerRespuestas().get(3))).get(2));
        
    }
    
    public void vaciarCampos(){
        _TxtFldGrupo1_1.setText("");
        _TxtFldGrupo1_2.setText("");
        _TxtFldGrupo1_3.setText("");
        _TxtFldGrupo2_1.setText("");
        _TxtFldGrupo2_2.setText("");
        _TxtFldGrupo2_3.setText("");
        _TxtFldGrupo3_1.setText("");
        _TxtFldGrupo3_2.setText("");
        _TxtFldGrupo3_3.setText("");
        _TxtFldGrupo4_1.setText("");
        _TxtFldGrupo4_2.setText("");
        _TxtFldGrupo4_3.setText("");
    }
    
        private RespuestaAgrupar generarRespuestasUsuario(){
        RespuestaAgrupar respuestas = new RespuestaAgrupar();
        ArrayList grupo1 = new ArrayList();
        ArrayList grupo2 = new ArrayList();
        ArrayList grupo3 = new ArrayList();
        ArrayList grupo4 = new ArrayList();
        
        grupo1.add(_TxtFldGrupo1_1.getText());
        grupo1.add(_TxtFldGrupo1_2.getText());
        grupo1.add(_TxtFldGrupo1_3.getText());
        grupo2.add(_TxtFldGrupo2_1.getText());
        grupo2.add(_TxtFldGrupo2_2.getText());
        grupo2.add(_TxtFldGrupo2_3.getText());
        grupo3.add(_TxtFldGrupo3_1.getText());
        grupo3.add(_TxtFldGrupo3_2.getText());
        grupo3.add(_TxtFldGrupo3_3.getText());
        grupo4.add(_TxtFldGrupo4_1.getText());
        grupo4.add(_TxtFldGrupo4_2.getText());
        grupo4.add(_TxtFldGrupo4_3.getText());
        
        respuestas.agregarGrupo(_LblGrupo1.getText(), grupo1);
        respuestas.agregarGrupo(_LblGrupo2.getText(), grupo2);
        respuestas.agregarGrupo(_LblGrupo3.getText(), grupo3);
        respuestas.agregarGrupo(_LblGrupo4.getText(), grupo4);
        
        return respuestas;
    }
        
    public void calificar(){
        
        
        for(int i = 0; i<_preguntas.obtenerNumPreguntas();i++){
            RespuestaAgrupar respuestas = _preguntas.obtenerRespuestas(i);
            RespuestaAgrupar respuestasUsuario = _preguntas.obtenerRespuestasUsuario(i);
            for(int j=0;j<respuestas.obtenerRespuestas().size();j++){
                ArrayList buenas = (ArrayList) respuestas.obtenerRespuestas().get(j);
                ArrayList usuario = (ArrayList) respuestasUsuario.obtenerRespuestas().get(j);
                for(int z=0;z<buenas.size();z++){
                    if(buenas.contains(usuario.get(z))/*buenas.get(z).equals(usuario.get(z))*/){
                        _calificacion++;
                    }
                }
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agrupar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agrupar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agrupar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agrupar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agrupar(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel _JPanel;
    private javax.swing.JLabel _LblGrupo1;
    private javax.swing.JLabel _LblGrupo2;
    private javax.swing.JLabel _LblGrupo3;
    private javax.swing.JLabel _LblGrupo4;
    private javax.swing.JTextField _TxtFldGrupo1_1;
    private javax.swing.JTextField _TxtFldGrupo1_2;
    private javax.swing.JTextField _TxtFldGrupo1_3;
    private javax.swing.JTextField _TxtFldGrupo2_1;
    private javax.swing.JTextField _TxtFldGrupo2_2;
    private javax.swing.JTextField _TxtFldGrupo2_3;
    private javax.swing.JTextField _TxtFldGrupo3_1;
    private javax.swing.JTextField _TxtFldGrupo3_2;
    private javax.swing.JTextField _TxtFldGrupo3_3;
    private javax.swing.JTextField _TxtFldGrupo4_1;
    private javax.swing.JTextField _TxtFldGrupo4_2;
    private javax.swing.JTextField _TxtFldGrupo4_3;
    private javax.swing.JLabel _lblInstruccion;
    private javax.swing.JLabel _lblPregunta;
    private javax.swing.JButton avanzar;
    private javax.swing.JButton regresar;
    private javax.swing.JButton terminarExamen;
    // End of variables declaration//GEN-END:variables
    private PreguntaAgrupar _preguntas = null;
    private int _posicion = 0;
    private int _calificacion = 0;
    private ControladorAgrupar _controlador = null;
}
