/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import controlador.ControladorLogin;
import javax.swing.JOptionPane;

/**
 *
 * @author CFManuel
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login2
     */
    public Login(ControladorLogin controlador) {
        initComponents();
        _controlador = controlador;
        JTxtFld_Contrasena.setEnabled(false);
        JTxtFld_Nombre.setText(null);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JTxtFld_Nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTxtFld_Contrasena = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        JBtn_Aceptar = new javax.swing.JButton();
        JBtn_Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name:");

        JTxtFld_Nombre.setText("Manuel Emeterio Couoh Flota");
        JTxtFld_Nombre.setToolTipText("Ejemplo: Nombres apellidoPaterno apellidoMaterno ");
        JTxtFld_Nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel2.setText("Password:");

        jCheckBox1.setText("Administrador");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        JBtn_Aceptar.setText("Aceptar");
        JBtn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_AceptarActionPerformed(evt);
            }
        });

        JBtn_Cancelar.setText("Cancelar");
        JBtn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTxtFld_Nombre)
                            .addComponent(JTxtFld_Contrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
                        .addGap(27, 27, 27))))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(JBtn_Aceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(JBtn_Cancelar)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTxtFld_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTxtFld_Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtn_Aceptar)
                    .addComponent(JBtn_Cancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_AceptarActionPerformed
        // TODO add your handling code here:
        String nombre = JTxtFld_Nombre.getText();
        String[] nombreSeparado = null;
        if(!nombre.isEmpty()){
            if ("pase44".equals(JTxtFld_Contrasena.getText())){
            
            }else{
                nombreSeparado = _controlador.separarNombre(nombre);
                _controlador.guardaUsuario(nombreSeparado[0], nombreSeparado[1], nombreSeparado[2]);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Favor de Rellenar el campo nombre");
        }
        
    }//GEN-LAST:event_JBtn_AceptarActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(JTxtFld_Contrasena.isEnabled()){
            JTxtFld_Contrasena.setEnabled(false);
            jLabel1.setText("Name:");
            JTxtFld_Nombre.setToolTipText("Ejemplo: Nombres apellidoPaterno apellidoMaterno");
        }else{
            JTxtFld_Contrasena.setEnabled(true);
            jLabel1.setText("User Name:");
            JTxtFld_Nombre.setToolTipText("Ingresar su nombre de Usuario");
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void JBtn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_CancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_JBtn_CancelarActionPerformed
    
    public String obtenerNombreUsuario(){
        return _nombreUsuario;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtn_Aceptar;
    private javax.swing.JButton JBtn_Cancelar;
    private javax.swing.JTextField JTxtFld_Contrasena;
    private javax.swing.JTextField JTxtFld_Nombre;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    private String _nombreUsuario;
    private Examen examen = null;
    ControladorLogin _controlador = null;
}
